### ISSUE TITLE
DobotSDK.py - moving to specified co-ordinates

### ISSUE THREAD

**Issue by ghost** [maxosprojects/open-dobot#29]
Hi, 
I was wondering whether you're planning to complete the DobotSDK '_moveTo' so that the arm moves to the angles calculated from the provided Cartesian co-ordinates?
Thanks

**Comment by maxosprojects** [comment]
Is there any reason why `MoveWithSpeed(self, x, y, z, maxSpeed, accel=None, toolRotation=None)` doesn't work for you?

**Comment by maxosprojects** [comment]
Closing this issue as there is no response from the topic starter.

Please re-open if you need further assistance.
