### ISSUE TITLE
include version of stock firmware in README criticisms section?

### ISSUE THREAD

**Issue by ivar** [maxosprojects/open-dobot#32]
Hey there,
As a newbie when it comes to embedded system, I've appreciated reading your criticisms of the stock dobot offerings. I'm wondering if your comments and comparisons are still as valid with the newer official 1.1  release of their firmware. Could you update your readme to include the versions of the firmware you're talking about ? 

Also, thanks for working on this project - I'm looking forward to getting into my Dobot once I get a few prerequisite tasks done first :)

**Comment by maxosprojects** [comment]
That is the list of what this project was called to address when compared to the stock firmware and not a "criticism list".

Nothing listed there is specific to the version, except for commands being dropped, which is stated as "seems to be fixed at expense of command rate".
Though this is something rather controversial as you still lose control when the arm gets in the unreachable area.

The protocol has not changed, neither the fact that none of it (software, hardware, schematics) has been released open-source.
